chore(deps): Bump version.quarkus from 3.35.3 to 3.35.4 (#33)
Bumps `version.quarkus` from 3.35.3 to 3.35.4.
Updates `io.quarkus:quarkus-bom` from 3.35.3 to 3.35.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.35.4</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51109">#51109</a>
- Smallrye OpenAPI generation for SSE with Multi return type generates
array type</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/53479">#53479</a>
- x-smallrye-profile Profile filtering not working properly</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/53798">#53798</a>
- Update remaining actions to pinned shas</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/53844">#53844</a>
- Bump smallrye-open-api.version from 4.3.0 to 4.3.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/53916">#53916</a>
- Add support for more Jackson annotations in generated reflection-free
serializers</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/53944">#53944</a>
- Bump the hibernate group with 9 updates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/53946">#53946</a>
- [3.35.1] Hibernate IllegalArgumentException is not a subtype</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/53964">#53964</a>
- StackOverflowError in Hibernate metadata processing since 3.35 for
generic <code>AttributeConverter</code></li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54060">#54060</a>
- Allow WebDependencyJarBuildItem to carry import mappings directly</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54085">#54085</a>
- Improve Micrometer test resilience</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/54091">#54091</a>
- mTLS auth mechanism throws NPE when proxy &quot;forwarded&quot; header
indicate HTTPS in the HTTP request</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/54093">#54093</a>
- Using reflection-free serializers breaks in 3.35</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/54127">#54127</a>
- quarkus-opentelemetry native image on JDK 25:
IllegalArgumentException: Receiver type ManagementSupport$$Lambda is not
an instance of com.sun.management.OperatingSystemMXBean at runtime</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54140">#54140</a>
- Fix CNFE for CpuMethods otel class</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/54146">#54146</a>
- SunPKCS provider is not available at runtime</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54147">#54147</a>
- Apply security provider specific configuration at runtime</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54148">#54148</a>
- Bump Narayana from 7.3.3.Final to 7.3.4.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54150">#54150</a>
- Bump the hibernate group across 1 directory with 14 updates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54188">#54188</a>
- Update JAXB to 4.0.8</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54189">#54189</a>
- Generate reflection-free Jackson serializers only for public
classes</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54199">#54199</a>
- docs: replace Markdown xml fence with AsciiDoc source block</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54208">#54208</a>
- Bump smallrye-open-api from 4.3.1 to 4.3.3</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54242">#54242</a>
- Prevent NPE in mTLS auth mech when communication with a trusted proxy
happens over HTTP protocol but headers indicate HTTPS</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54264">#54264</a>
- Fix NPE in RemoteUserAttribute with anonymous identity</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/54310">#54310</a>
- Prometheus compression header fix</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/1c1e9c67dfd71c7c3b9c134c92e4d726f61c5f0e"><code>1c1e9c6</code></a>
[RELEASE] - Bump version to 3.35.4</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/6167502d027480e7460448e256c485b90141178b"><code>6167502</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/54328">#54328</a>
from gsmet/3.35.4-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/337bfcfd653146adba5d2a1ba990a785a13f70c7"><code>337bfcf</code></a>
fix(security): prevent NPE in mTLS auth mech &amp; trusted proxy</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/86fa317fb457d3c5bdba135160045f007a6a83e2"><code>86fa317</code></a>
Fix NPE in RemoteUserAttribute with anonymous identity</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/e111dc1fec9e90b58f1626c7e852d3bb75ef0bd6"><code>e111dc1</code></a>
Prometheus compression header fix</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/0b22ecd6139a346b325afdb8d339e5a3807abc33"><code>0b22ecd</code></a>
improve Micrometer test resilience</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/353fb872b6a6ed0c1a824159825350515033837a"><code>353fb87</code></a>
Bump smallrye-open-api from 4.3.1 to 4.3.3</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/58c97a9f10bbdca86f1a7e24511766dbdbb7ea99"><code>58c97a9</code></a>
Bump the hibernate group across 1 directory with 14 updates</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/ca4182f222e8377c3fb19cc64b90d458473e6f4e"><code>ca4182f</code></a>
Bump the hibernate group with 9 updates</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/129eb849fcf01306ba3ff2c8c7626c6b7fcf6b54"><code>129eb84</code></a>
Update JAXB to 4.0.8</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.35.3...3.35.4">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus:quarkus-maven-plugin` from 3.35.3 to 3.35.4


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>